#!/bin/bash

tmp=20
while [ $tmp -ne 0 ]
do
	url=$(curl --max-time 10 --retry 3 --retry-delay 5 --retry-max-time 32 -s -D- -L -o /dev/null http://epg.kodibg.org/dl.php | sed -n -e 's:.*\(http.*epg\.xml\.gz\).*:\1:p')
	if [ -n "$url" ]
	then
		curl --max-time 10 --retry 3 --retry-delay 5 --retry-max-time 32 -s -L -o- $url | gunzip -c
		break
	fi
	sleep 3
	tmp=$((tmp-1))
done
